# Generated by Django 4.2.2 on 2023-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
