# Generated by Django 4.2.2 on 2023-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_profile_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
